### ISSUE TITLE
idhash.c:1:10: fatal error: 'bignum.c' file not found when using v 0.1.1.1 and 0.1.1.2

### ISSUE THREAD

**Issue by MFRWDesign** [Nakilon/dhash-vips#5]
Came across this bug today while trying to bundle install our project. Posting this issue in case it's of some help to someone else. I tried to track it down but couldn't find anything that helped (including `brew reinstall vips`, `brew upgrade && brew update`.

Eventually I fixed the bundling error for dhash-vips by rolling the version specified in the Gemfile back to '0.1.1'.

I'm running:
OS X 10.15.5
Homebrew 2.5.1
Ruby 2.7.1 (via rbenv v1.1.2)

(I suspect the problem to have arisen from the changes to extconf.rb in this commit: http://github.com/Nakilon/dhash-vips/commit/56fba57aac82552f26086474cd57b63a4a99dc36%20 but I can't be sure as I wasn't able to verify any fix.)

**Comment by ynelin** [comment]
Hi
Same problem with 0.1.1.2 and 0.1.1.1. Works fine on 0.1.1

```
current directory: /Users/yarik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dhash-vips-0.1.1.2
make "DESTDIR=" clean

current directory: /Users/yarik/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dhash-vips-0.1.1.2
make "DESTDIR="
compiling idhash.c
idhash.c:1:10: fatal error: 'bignum.c' file not found
#include <bignum.c>
         ^~~~~~~~~~
1 error generated.
make: *** [idhash.o] Error 1

make failed, exit code 2
```

**Comment by Nakilon** [comment]
Thank you guys for the bug report!
Probably I should make some Github Action to test the installation process.

`bignum.c` is a part of Ruby source code that is needed for compilation if you want the fingerprint comparison to be 15 times faster. Essentially the `'bignum.c' file not found` means that **you didn't use flag `-k` in `rbenv install`. Did you?**
It should be handled and just skip the compilation of the native extension though. Maybe in last releases I broke it and forgot to check.

**Comment by Nakilon** [comment]
@MFRWDesign @ynelin please, check if 0.1.1.3 works for you.

**Comment by ynelin** [comment]
> @MFRWDesign @ynelin please, check if 0.1.1.3 works for you and I'll yank 0.1.1.2, 0.1.1.1.

Thank's, works fine now
